### ISSUE TITLE
Incorrect exception messages in LicenseKey

### ISSUE THREAD

**Issue by sergey-oplavin** [Cryptolens/cryptolens-java#22]
Hello team, 
I accidentally found that in case of some errors, an incorrect exception messages is printed into the error stream, e.g.:
`[Ljava.lang.StackTraceElement;@5d91ae08`

This happens because of two places in the LicenseKey code where `System.err.println(ex.getStackTrace());` is used:
[here](https://github.com/Cryptolens/cryptolens-java/blob/c4fec3f1f01d709cb369dae97dbb863e460907a7/src/main/java/io/cryptolens/models/LicenseKey.java#L88) and [here](https://github.com/Cryptolens/cryptolens-java/blob/c4fec3f1f01d709cb369dae97dbb863e460907a7/src/main/java/io/cryptolens/models/LicenseKey.java#L105)

The fix might be to just replace it with: `ex.printStackTrace(System.err);`

**Comment by artemlos** [comment]
@sergey-oplavin thank you for the feedback!

We will update this in the next release of the Java SDK.

/ Artem

**Comment by artemlos** [comment]
The fix is now available in v1.21 (https://github.com/Cryptolens/cryptolens-java/releases/tag/v1.21)
