### ISSUE TITLE
Offline activation requires productId check

### ISSUE THREAD

**Issue by sergey-oplavin** [Cryptolens/cryptolens-java#23]
Hello team,
We have faced an issue with the offline activation - `LicenseKey.LoadFromString(key, licenseContent)` method does not check a product ID, so it's possible to get a valid key for an activation file for a different product. 
I think this is fine, since we can easily check the product ID once we have a LicenseKey object, but it might not very obvious for new users that this check needs to be done, since there is no mention in the documentation. Also, online activation methods -  `Key.Activate` does product ID check already, so I would expect the same behavior for the offline activation.

Having said that, I think it would be nice to either add a few words about the necessity of product ID check into the documentation: https://github.com/Cryptolens/cryptolens-java#offline-activation-savingloading-licenses
Or to add an additional 'productId' parameter into `LicenseKey.LoadFromString` methods.

**Comment by artemlos** [comment]
Hi @sergey-oplavin,

Thank you for the feedback. That is a good point; there is now a note on that in the *Offline activation* section https://github.com/Cryptolens/cryptolens-java/commit/d36545d0368cb6cca5488d6536fedbc7e7d70836

**Comment by sergey-oplavin** [comment]
Hi @artemlos, thanks for adding a note on that
