### ISSUE TITLE
Concerning Android node locking feature

### ISSUE THREAD

**Issue by chromaticnoob** [Cryptolens/cryptolens-java#29]
First of all, this API is amazing. It facilitated the entire licensing process and it works like a charm, and with pretty good security too.

Anyway, I developed a licensed Android app and I tried to get my product's licenses node-locked, that is, generating ANDROID_IDs and checking whether the keys are on the right machines. I always got errors saying that the licenses are not on the right machine although their IDs are correctly registered on the Web CPanel. The docs say I should call 'isOnRightMachine' with parameter v=2 if I am using Cryptolens-android.jar

There is another section of the documentation that says that 'getMachineCode' doesn't work on Android, which is correct. Which is why I had to generate Android IDs to identify a device, despite their shortcoming. However, I had to analyze the source code to know that 'isOnRightMachine' actually has a paramter that says 'machine code', that is not explicitly mentioned anywhere in the docs. It would be pretty useful if you inform Android Devs to explicitly specify the machine code in 'isOnRightMachine()' parameters instead of setting v = 2.

Also, concerning Android IDs, for now they're pretty much the only reliable identifier for newer Android versions. An Android ID will reset upon factory reset, but also, if the Android version is 8.0 or higher, the Android IDs is unique to the operating system, the device's user, AND the app's signing key itself. That's why you also have to inform the devs that using Android IDs should only reliable when you have a STATIC app signature key across all devices, all updates, all releases..etc

It's worth mentioning that 'getDeviceId()' does not work anymore due to the impossible permission it requires (PRIVILEGED_READ_PHONE_STATE) which requires the device to be in 'Enterprise Mode' (no normal end-users have this on).

Cheers!

**Comment by artemlos** [comment]
Hi @chromaticnoob, thanks for the detailed feedback! I'm sorry for a delayed reply.

I made an update in the documentation for Android developers that refers to a [wiki article](https://help.cryptolens.io/getting-started/ios-android) that covers different ways to compute the device ID and how it can be passed on as a parameter to Helpers.GetMachineCode.

From what we know, there are two ways to compute a device fingerprint on Android, both with their pros and cons.

A method that does not require any extra permission (last time we checked) is the Android_ID, which can be computed as follows:

```java
String machineCode = Secure.getString(this.getContentResolver(), Secure.ANDROID_ID);
```

The other way is to use the getDeviceId(), which, as you said, requires additional permission but may not always work.
