### ISSUE TITLE
Receiving 401 error while trying to activate a key

### ISSUE THREAD

**Issue by audciz** [Cryptolens/cryptolens-java#31]
Hello,
I'm receiving 401 error (WebAPIError) while trying to activate a key with Java library.
I'm using v1.25 of Cryptolens. I've tried both android and non-android versions of library.

My code below:
```
private static void checkLicense() {
    String RSAPubKey = "MyRSAPubKey";
    String auth = "MyAuthKey";
    
    LicenseKey license = null;
    String licenseFilePath = "./de_license.lic";
    String licenseKeyPath = "./key.txt";
    APIError error = new APIError();

    try {
        String licenseString = new String(Files.readAllBytes(Paths.get(licenseFilePath)));
        license = LicenseKey.LoadFromString(RSAPubKey, licenseString, 30);
    } catch (IOException ein) {
        try {
            String licenseKey = new String(Files.readAllBytes(Paths.get(licenseKeyPath)));
            license = Key.Activate(auth, RSAPubKey, new ActivateModel(14771, licenseKey, Helpers.GetMachineCode(2)), error);
            System.out.println(error.message);
            System.out.println(error.errorType);

            if (Helpers.IsOnRightMachine(license, 2)) {
                try {
                    BufferedWriter writer = new BufferedWriter(new FileWriter(licenseFilePath));
                    writer.write(license.SaveAsString());
                    writer.close();
                } catch (IOException ignored) {
                }
            }
        } catch (IOException ignored) {
        }
    }

    if (!Helpers.IsOnRightMachine(license, 2)) {
        throw new IllegalArgumentException("Wrong license key!");
    }
}
```

**Comment by artemlos** [comment]
@audciz thanks for your question.

Could you please check what the detailed error message is? It is stored in the error object inside the `message` field.

Another way to find out the API error is by calling the API directly through the browser. I will include a link where there is an example on how it can be done: https://help.cryptolens.io/faq/index#troubleshooting-api-errors

Since it appears to be an API error and not an issue with the SDK, I will close this issue on GitHub. I would instead suggest to send it to support@cryptolens.io, since this will allow us to troubleshoot it further.

Thanks again!

**Comment by artemlos** [comment]
@audciz After reviewing the code again, it looks like it could be an issue with the RSA Public Key, i.e., that there is a typo. It does not seem to be related to the Web API, at least based on the code that you sent. If possible, please send us the code with the RSA Public Key and we can check what might have gone wrong. Thanks!

**Comment by audciz** [comment]
Hello Artem,

Thank you for your response and sorry for the late reply!

I've tried to make the same request with the postman and received an error
message, that I haven't had an active subscription.
Somehow the response using the SDK is unambiguous, but the response from
the direct request is more informative.

Kind regards,
Arman Kurmanbay

**Comment by artemlos** [comment]
@audciz Thanks for the feedback! We will check how this can be improved and release it in a future release.

Thanks again!
